name = "App"
uuid = "85a2e9fd-6b09-4cf9-9203-8f95abbd6aef"
authors = ["Jaan Tollander de Balsch <jaan.tollander.de.balsch@csc.fi>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"

[compat]
julia = "1.8"
